services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scm-backend
    restart: no
    environment:
      JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RESEND_API_KEY: ${RESEND_API_KEY}
      MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL:-onboarding@resend.dev}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-43200000}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH2_REDIRECT_URI: ${OAUTH2_REDIRECT_URI:-http://localhost:5173/oauth2/callback}
    ports:
      - "8080:8080"
